language: python

python:
- '3.8'

install:
- pip install -r requirements.txt

script:
- make lint
- pytest --cov=snflambda

notifications:
  email:
    on_success: never
    on_failure: always

deploy:
  provider: script
  script: echo 'hello world'
